const mockUsers = [
  {
      "id": 5,
      "username": "bceid\\nackyu711",
      "clientId": null,
      "givenName": "han",
      "familyName": "Han Nackyu",
      "email": "nackyu711@gmail.com",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 6,
      "username": "shellhan",
      "clientId": null,
      "givenName": "Shelly",
      "familyName": "Han",
      "email": "shelly+1@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 7,
      "username": "bceid\\jasoncleach",
      "clientId": null,
      "givenName": "Jason",
      "familyName": "Leach",
      "email": "jason.leach@fullboar.ca",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 8,
      "username": "bceid\\myraah1",
      "clientId": null,
      "givenName": "Agreement Holder 1",
      "familyName": "Range",
      "email": "roop@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 9,
      "username": "bceid\\phillbillips",
      "clientId": null,
      "givenName": "Phill",
      "familyName": "Billips",
      "email": "pb@example.com",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 11,
      "username": "idir\\lujones",
      "clientId": null,
      "givenName": "Lucy",
      "familyName": "Jones",
      "email": "lucy.jones@gov.bc.ca",
      "phoneNumber": "250-394-4703",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 43,
      "username": "idir\\slarade",
      "clientId": null,
      "givenName": "Shawna",
      "familyName": "Larade",
      "email": "shawna.larade@gov.bc.ca",
      "phoneNumber": "250-489-8555",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 16,
      "username": "idir\\hmcintyr",
      "clientId": null,
      "givenName": "Hanna",
      "familyName": "McIntyre",
      "email": "hanna.mcintyre@gov.bc.ca",
      "phoneNumber": "250-489-8548",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 17,
      "username": "idir\\cahaywoo",
      "clientId": null,
      "givenName": "Cara",
      "familyName": "Haywood-Farmer",
      "email": "cara.haywood-farmer@gov.bc.ca",
      "phoneNumber": "250-378-8404",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 18,
      "username": "idir\\pgyug",
      "clientId": null,
      "givenName": "Philip",
      "familyName": "Gyug",
      "email": "philip.gyug@gov.bc.ca",
      "phoneNumber": "250-378-8476",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 44,
      "username": "idir\\keastwoo",
      "clientId": null,
      "givenName": "Kevin",
      "familyName": "Eastwood",
      "email": "kevin.eastwood@gov.bc.ca",
      "phoneNumber": "250-317-7849",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 25,
      "username": "idir\\marcamer",
      "clientId": null,
      "givenName": "Marika",
      "familyName": "Cameron",
      "email": "marika.cameron@gov.bc.ca",
      "phoneNumber": "250-784-1293",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 24,
      "username": "idir\\mkc",
      "clientId": null,
      "givenName": "Mahesh",
      "familyName": "Kc",
      "email": "mahesh.kc@gov.bc.ca",
      "phoneNumber": "250-784-1200",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 26,
      "username": "idir\\ebasset",
      "clientId": null,
      "givenName": "Eleanor",
      "familyName": "Bassett",
      "email": "eleanor.bassett@gov.bc.ca",
      "phoneNumber": "250-395-7874",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 28,
      "username": "idir\\kjchalme",
      "clientId": null,
      "givenName": "Ken",
      "familyName": "Chalmers",
      "email": "ken.chalmers@gov.bc.ca",
      "phoneNumber": "251-692-2238",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 29,
      "username": "idir\\sllatin",
      "clientId": null,
      "givenName": "Sandra",
      "familyName": "Latin",
      "email": "sandra.latin@gov.bc.ca",
      "phoneNumber": "250-992-4482",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 30,
      "username": "idir\\tsinger",
      "clientId": null,
      "givenName": "Tim",
      "familyName": "Singer",
      "email": "tim.singer@gov.bc.ca",
      "phoneNumber": "250-992-4415",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 31,
      "username": "idir\\msalzl",
      "clientId": null,
      "givenName": "Mark",
      "familyName": "Salzl",
      "email": "mark.salzl@gov.bc.ca",
      "phoneNumber": "250-559-6206",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 32,
      "username": "idir\\kwitt",
      "clientId": null,
      "givenName": "Kyra",
      "familyName": "Witt",
      "email": "kyra.witt@gov.bc.ca",
      "phoneNumber": "250-550-2244",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 33,
      "username": "idir\\smort",
      "clientId": null,
      "givenName": "Sarah",
      "familyName": "Mortenson",
      "email": "sarah.mortenson@gov.bc.ca",
      "phoneNumber": "250-550-2214",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 34,
      "username": "idir\\hhethering",
      "clientId": null,
      "givenName": "Harold",
      "familyName": "Hetherington",
      "email": "harold.hetherington@gov.bc.ca",
      "phoneNumber": "250-260-4605",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 35,
      "username": "idir\\coduro",
      "clientId": null,
      "givenName": "Charles",
      "familyName": "Oduro",
      "email": "charles.oduro@gov.bc.ca",
      "phoneNumber": "250-260-4614",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 36,
      "username": "idir\\amsmeeth",
      "clientId": null,
      "givenName": "Aaron",
      "familyName": "Smeeth",
      "email": "aaron.smeeth@gov.bc.ca",
      "phoneNumber": "778-647-2002",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 45,
      "username": "idir\\jawoods",
      "clientId": null,
      "givenName": "Jane",
      "familyName": "Woods",
      "email": "jane.woods@gov.bc.ca",
      "phoneNumber": "250-847-6364",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 37,
      "username": "idir\\kltabe",
      "clientId": null,
      "givenName": "Karen",
      "familyName": "Tabe",
      "email": "karen.tabe@gov.bc.ca",
      "phoneNumber": "238-409-2004",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 38,
      "username": "idir\\kbarton",
      "clientId": null,
      "givenName": "Krista",
      "familyName": "Barton",
      "email": "krista.barton@gov.bc.ca",
      "phoneNumber": "250-371-6549",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 46,
      "username": "idir\\carussel",
      "clientId": null,
      "givenName": "Caitlin",
      "familyName": "Russell",
      "email": "caitlin.russell@gov.bc.ca",
      "phoneNumber": "250-748-1275",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 48,
      "username": "idir\\dmbuis",
      "clientId": null,
      "givenName": "Drew",
      "familyName": "Buis",
      "email": "drew.buis@gov.bc.ca",
      "phoneNumber": "250-395-7895",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 49,
      "username": "idir\\rdinwood",
      "clientId": null,
      "givenName": "Rob",
      "familyName": "Dinwoodie",
      "email": "rob.dinwoodie@gov.bc.ca",
      "phoneNumber": "250-558-1768",
      "active": true,
      "lastLoginAt": null
  },
  {
      "id": 50,
      "username": "idir\\cdumais",
      "clientId": null,
      "givenName": "Cardell",
      "familyName": "Dumais",
      "email": "cardell.dumais@gov.bc.ca",
      "phoneNumber": "250-371-6607",
      "active": true,
      "lastLoginAt": "2018-11-20T21:28:38.412Z"
  },
  {
      "id": 19,
      "username": "idir\\rawhiteh",
      "clientId": null,
      "givenName": "Rachel",
      "familyName": "Whitehouse",
      "email": "rachel.whitehouse@gov.bc.ca",
      "phoneNumber": "250-378-8406",
      "active": true,
      "lastLoginAt": "2018-11-21T20:51:06.127Z"
  },
  {
      "id": 51,
      "username": "idir\\cfell",
      "clientId": null,
      "givenName": "Cynthia",
      "familyName": "Fell",
      "email": "cynthia.fell@gov.bc.ca",
      "phoneNumber": "250-398-4321",
      "active": true,
      "lastLoginAt": "2018-11-22T22:27:46.912Z"
  },
  {
      "id": 53,
      "username": "idir\\smortens",
      "clientId": null,
      "givenName": "Sarah",
      "familyName": "Mortenson",
      "email": "sarah.mortenson@gov.bc.ca",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-11-21T20:53:20.750Z"
  },
  {
      "id": 21,
      "username": "idir\\rgarciad",
      "clientId": null,
      "givenName": "Rene",
      "familyName": "Garcia-Daguer",
      "email": "rene.garciadaguer@gov.bc.ca",
      "phoneNumber": "250-378-8477",
      "active": true,
      "lastLoginAt": "2018-11-27T21:25:03.790Z"
  },
  {
      "id": 22,
      "username": "idir\\asiemen",
      "clientId": null,
      "givenName": "Alisa",
      "familyName": "Siemens",
      "email": "alisa.siemens@gov.bc.ca",
      "phoneNumber": "250-442-5426",
      "active": true,
      "lastLoginAt": "2018-11-28T17:31:12.827Z"
  },
  {
      "id": 41,
      "username": "idir\\zoesimon",
      "clientId": null,
      "givenName": "Zoe",
      "familyName": "Simon",
      "email": "zoe.simon@gov.bc.ca",
      "phoneNumber": "250-371-6500",
      "active": true,
      "lastLoginAt": "2018-11-28T21:48:04.376Z"
  },
  {
      "id": 3,
      "username": "kyubinhan",
      "clientId": null,
      "givenName": "Kyubin",
      "familyName": "Han",
      "email": "kyubinhan@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-11-20T00:41:20.213Z"
  },
  {
      "id": 12,
      "username": "idir\\carmes",
      "clientId": null,
      "givenName": "Chris",
      "familyName": "Armes",
      "email": "chris.armes@gov.bc.ca",
      "phoneNumber": "250-398-4362",
      "active": true,
      "lastLoginAt": "2018-11-28T17:12:58.723Z"
  },
  {
      "id": 39,
      "username": "idir\\bwheatle",
      "clientId": null,
      "givenName": "Barb",
      "familyName": "Wheatley",
      "email": "barb.wheatley@gov.bc.ca",
      "phoneNumber": "250-371-6500",
      "active": true,
      "lastLoginAt": "2018-11-28T22:13:24.387Z"
  },
  {
      "id": 27,
      "username": "idir\\dilbrown",
      "clientId": null,
      "givenName": "Diane",
      "familyName": "Brown",
      "email": "diane.l.brown@gov.bc.ca",
      "phoneNumber": "250-395-7815",
      "active": true,
      "lastLoginAt": "2018-11-22T19:46:50.420Z"
  },
  {
      "id": 13,
      "username": "idir\\kjames",
      "clientId": null,
      "givenName": "Kassia",
      "familyName": "James",
      "email": "kassia.james@gov.bc.ca",
      "phoneNumber": "250-398-4364",
      "active": true,
      "lastLoginAt": "2018-11-27T18:24:25.960Z"
  },
  {
      "id": 65,
      "username": "bceid\\rangeadmin",
      "clientId": null,
      "givenName": "range",
      "familyName": "admin",
      "email": "rangeadmin@myrangebc.gov.ca",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-11-27T19:38:43.406Z"
  },
  {
      "id": 52,
      "username": "idir\\krbarton",
      "clientId": null,
      "givenName": "Krista",
      "familyName": "Barton",
      "email": "krista.barton@gov.bc.ca",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-11-26T16:47:15.965Z"
  },
  {
      "id": 14,
      "username": "idir\\momuelle",
      "clientId": null,
      "givenName": "Morgan",
      "familyName": "Mueller",
      "email": "morgan.mueller@gov.bc.ca",
      "phoneNumber": "250-398-4364",
      "active": true,
      "lastLoginAt": "2018-11-22T18:15:13.515Z"
  },
  {
      "id": 42,
      "username": "idir\\saschwar",
      "clientId": null,
      "givenName": "Sarah",
      "familyName": "Schwarz",
      "email": "sarah.schwarz@gov.bc.ca",
      "phoneNumber": "250-442-4386",
      "active": true,
      "lastLoginAt": "2018-12-04T19:32:29.909Z"
  },
  {
      "id": 15,
      "username": "idir\\maschuff",
      "clientId": null,
      "givenName": "Marc",
      "familyName": "Schuffert",
      "email": "marc.schuffert@gov.bc.ca",
      "phoneNumber": "250-847-6329",
      "active": true,
      "lastLoginAt": "2018-12-03T21:51:24.751Z"
  },
  {
      "id": 10,
      "username": "idir\\tnairn",
      "clientId": null,
      "givenName": "Trish",
      "familyName": "Nairn",
      "email": "trish.nairn@gov.bc.ca",
      "phoneNumber": "250-398-4242",
      "active": true,
      "lastLoginAt": "2018-11-22T23:10:58.284Z"
  },
  {
      "id": 23,
      "username": "idir\\tgrafton",
      "clientId": null,
      "givenName": "Taylor",
      "familyName": "Grafton",
      "email": "taylor.grafton@gov.bc.ca",
      "phoneNumber": "250-614-7427",
      "active": true,
      "lastLoginAt": "2018-11-22T00:15:10.036Z"
  },
  {
      "id": 1,
      "username": "rangestaff",
      "clientId": null,
      "givenName": "Range",
      "familyName": "Staff",
      "email": "amir+1@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-12-03T20:18:22.840Z"
  },
  {
      "id": 47,
      "username": "idir\\willshaw",
      "clientId": null,
      "givenName": "William",
      "familyName": "Shaw",
      "email": "william.shaw@gov.bc.ca",
      "phoneNumber": "250-784-1239",
      "active": true,
      "lastLoginAt": "2018-11-22T16:23:33.186Z"
  },
  {
      "id": 66,
      "username": "idir\\lmoore",
      "clientId": null,
      "givenName": "Lisa",
      "familyName": "Moore",
      "email": "lisa.moore@gov.bc.ca",
      "phoneNumber": null,
      "active": false,
      "lastLoginAt": "2018-11-27T17:15:27.602Z"
  },
  {
      "id": 40,
      "username": "idir\\avolo",
      "clientId": null,
      "givenName": "Andrew",
      "familyName": "Volo",
      "email": "andrew.volo@gov.bc.ca",
      "phoneNumber": "250-371-6222",
      "active": true,
      "lastLoginAt": "2018-11-28T17:51:15.953Z"
  },
  {
      "id": 63,
      "username": "bceid\\rangestaff",
      "clientId": null,
      "givenName": "Range",
      "familyName": "Staff",
      "email": "rangestaff@myrange.gov.ca",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-11-27T00:47:12.364Z"
  },
  {
      "id": 2,
      "username": "rangeadmin",
      "clientId": null,
      "givenName": "Range",
      "familyName": "Admin",
      "email": "kyubin+1@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-12-05T00:29:01.859Z"
  },
  {
      "id": 4,
      "username": "bceid\\kyubinhan711",
      "clientId": null,
      "givenName": "Kyub",
      "familyName": "Han",
      "email": "kyubin@freshworks.io",
      "phoneNumber": null,
      "active": true,
      "lastLoginAt": "2018-12-04T23:35:24.812Z"
  },
  {
      "id": 20,
      "username": "idir\\rmctavis",
      "clientId": null,
      "givenName": "Ried",
      "familyName": "McTavish",
      "email": "ried.mctavish@gov.bc.ca",
      "phoneNumber": "250-378-8487",
      "active": true,
      "lastLoginAt": "2018-12-05T00:02:13.135Z"
  }
];

export default mockUsers;
