const mockClients = [
  {
    clientNumber: '00076818',
    locationCodes: ['00'],
    name: 'BLANABBA, FREWT',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999901',
    locationCodes: ['01'],
    name: 'Leslie Knope',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999906',
    locationCodes: ['01'],
    name: 'Ann Perkins',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999903',
    locationCodes: ['01'],
    name: 'Tom Haverford',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999905',
    locationCodes: ['01'],
    name: 'April Ludgate',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999909',
    locationCodes: ['01'],
    name: 'Andy Dwyer',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999910',
    locationCodes: ['01'],
    name: 'Nackyu Han',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999907',
    locationCodes: ['01'],
    name: 'Ben Wyatt',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999902',
    locationCodes: ['01'],
    name: 'Ron Swanson',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
  {
    clientNumber: '09999908',
    locationCodes: ['01'],
    name: 'Chris Traeger',
    licenseeStartDate: null,
    licenseeEndDate: null,
    clientType: {},
  },
];

export default mockClients;
