const mockUsers = [
  {
    id: 5,
    username: 'bceid\\nackyu711',
    clients: [],
    givenName: 'han',
    familyName: 'Han Nackyu',
    email: 'nackyu711@gmail.com',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  },
  {
    id: 6,
    username: 'shellhan',
    clients: [],
    givenName: 'Shelly',
    familyName: 'Han',
    email: 'shelly+1@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  },
  {
    id: 7,
    username: 'bceid\\jasoncleach',
    clients: [],
    givenName: 'Jason',
    familyName: 'Leach',
    email: 'jason.leach@fullboar.ca',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  },
  {
    id: 8,
    username: 'bceid\\myraah1',
    clients: [],
    givenName: 'Agreement Holder 1',
    familyName: 'Range',
    email: 'roop@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  },
  {
    id: 9,
    username: 'bceid\\phillbillips',
    clients: [],
    givenName: 'Phill',
    familyName: 'Billips',
    email: 'pb@example.com',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  },
  {
    id: 11,
    username: 'idir\\lujones',
    clients: [],
    givenName: 'Lucy',
    familyName: 'Jones',
    email: 'lucy.jones@gov.bc.ca',
    phoneNumber: '250-394-4703',
    active: true,
    lastLoginAt: null
  },
  {
    id: 43,
    username: 'idir\\slarade',
    clients: [],
    givenName: 'Shawna',
    familyName: 'Larade',
    email: 'shawna.larade@gov.bc.ca',
    phoneNumber: '250-489-8555',
    active: true,
    lastLoginAt: null
  },
  {
    id: 16,
    username: 'idir\\hmcintyr',
    clients: [],
    givenName: 'Hanna',
    familyName: 'McIntyre',
    email: 'hanna.mcintyre@gov.bc.ca',
    phoneNumber: '250-489-8548',
    active: true,
    lastLoginAt: null
  },
  {
    id: 17,
    username: 'idir\\cahaywoo',
    clients: [],
    givenName: 'Cara',
    familyName: 'Haywood-Farmer',
    email: 'cara.haywood-farmer@gov.bc.ca',
    phoneNumber: '250-378-8404',
    active: true,
    lastLoginAt: null
  },
  {
    id: 18,
    username: 'idir\\pgyug',
    clients: [],
    givenName: 'Philip',
    familyName: 'Gyug',
    email: 'philip.gyug@gov.bc.ca',
    phoneNumber: '250-378-8476',
    active: true,
    lastLoginAt: null
  },
  {
    id: 44,
    username: 'idir\\keastwoo',
    clients: [],
    givenName: 'Kevin',
    familyName: 'Eastwood',
    email: 'kevin.eastwood@gov.bc.ca',
    phoneNumber: '250-317-7849',
    active: true,
    lastLoginAt: null
  },
  {
    id: 25,
    username: 'idir\\marcamer',
    clients: [],
    givenName: 'Marika',
    familyName: 'Cameron',
    email: 'marika.cameron@gov.bc.ca',
    phoneNumber: '250-784-1293',
    active: true,
    lastLoginAt: null
  },
  {
    id: 24,
    username: 'idir\\mkc',
    clients: [],
    givenName: 'Mahesh',
    familyName: 'Kc',
    email: 'mahesh.kc@gov.bc.ca',
    phoneNumber: '250-784-1200',
    active: true,
    lastLoginAt: null
  },
  {
    id: 26,
    username: 'idir\\ebasset',
    clients: [],
    givenName: 'Eleanor',
    familyName: 'Bassett',
    email: 'eleanor.bassett@gov.bc.ca',
    phoneNumber: '250-395-7874',
    active: true,
    lastLoginAt: null
  },
  {
    id: 28,
    username: 'idir\\kjchalme',
    clients: [],
    givenName: 'Ken',
    familyName: 'Chalmers',
    email: 'ken.chalmers@gov.bc.ca',
    phoneNumber: '251-692-2238',
    active: true,
    lastLoginAt: null
  },
  {
    id: 29,
    username: 'idir\\sllatin',
    clients: [],
    givenName: 'Sandra',
    familyName: 'Latin',
    email: 'sandra.latin@gov.bc.ca',
    phoneNumber: '250-992-4482',
    active: true,
    lastLoginAt: null
  },
  {
    id: 30,
    username: 'idir\\tsinger',
    clients: [],
    givenName: 'Tim',
    familyName: 'Singer',
    email: 'tim.singer@gov.bc.ca',
    phoneNumber: '250-992-4415',
    active: true,
    lastLoginAt: null
  },
  {
    id: 31,
    username: 'idir\\msalzl',
    clients: [],
    givenName: 'Mark',
    familyName: 'Salzl',
    email: 'mark.salzl@gov.bc.ca',
    phoneNumber: '250-559-6206',
    active: true,
    lastLoginAt: null
  },
  {
    id: 32,
    username: 'idir\\kwitt',
    clients: [],
    givenName: 'Kyra',
    familyName: 'Witt',
    email: 'kyra.witt@gov.bc.ca',
    phoneNumber: '250-550-2244',
    active: true,
    lastLoginAt: null
  },
  {
    id: 33,
    username: 'idir\\smort',
    clients: [],
    givenName: 'Sarah',
    familyName: 'Mortenson',
    email: 'sarah.mortenson@gov.bc.ca',
    phoneNumber: '250-550-2214',
    active: true,
    lastLoginAt: null
  },
  {
    id: 34,
    username: 'idir\\hhethering',
    clients: [],
    givenName: 'Harold',
    familyName: 'Hetherington',
    email: 'harold.hetherington@gov.bc.ca',
    phoneNumber: '250-260-4605',
    active: true,
    lastLoginAt: null
  },
  {
    id: 35,
    username: 'idir\\coduro',
    clients: [],
    givenName: 'Charles',
    familyName: 'Oduro',
    email: 'charles.oduro@gov.bc.ca',
    phoneNumber: '250-260-4614',
    active: true,
    lastLoginAt: null
  },
  {
    id: 36,
    username: 'idir\\amsmeeth',
    clients: [],
    givenName: 'Aaron',
    familyName: 'Smeeth',
    email: 'aaron.smeeth@gov.bc.ca',
    phoneNumber: '778-647-2002',
    active: true,
    lastLoginAt: null
  },
  {
    id: 45,
    username: 'idir\\jawoods',
    clients: [],
    givenName: 'Jane',
    familyName: 'Woods',
    email: 'jane.woods@gov.bc.ca',
    phoneNumber: '250-847-6364',
    active: true,
    lastLoginAt: null
  },
  {
    id: 37,
    username: 'idir\\kltabe',
    clients: [],
    givenName: 'Karen',
    familyName: 'Tabe',
    email: 'karen.tabe@gov.bc.ca',
    phoneNumber: '238-409-2004',
    active: true,
    lastLoginAt: null
  },
  {
    id: 38,
    username: 'idir\\kbarton',
    clients: [],
    givenName: 'Krista',
    familyName: 'Barton',
    email: 'krista.barton@gov.bc.ca',
    phoneNumber: '250-371-6549',
    active: true,
    lastLoginAt: null
  },
  {
    id: 46,
    username: 'idir\\carussel',
    clients: [],
    givenName: 'Caitlin',
    familyName: 'Russell',
    email: 'caitlin.russell@gov.bc.ca',
    phoneNumber: '250-748-1275',
    active: true,
    lastLoginAt: null
  },
  {
    id: 48,
    username: 'idir\\dmbuis',
    clients: [],
    givenName: 'Drew',
    familyName: 'Buis',
    email: 'drew.buis@gov.bc.ca',
    phoneNumber: '250-395-7895',
    active: true,
    lastLoginAt: null
  },
  {
    id: 49,
    username: 'idir\\rdinwood',
    clients: [],
    givenName: 'Rob',
    familyName: 'Dinwoodie',
    email: 'rob.dinwoodie@gov.bc.ca',
    phoneNumber: '250-558-1768',
    active: true,
    lastLoginAt: null
  },
  {
    id: 50,
    username: 'idir\\cdumais',
    clients: [],
    givenName: 'Cardell',
    familyName: 'Dumais',
    email: 'cardell.dumais@gov.bc.ca',
    phoneNumber: '250-371-6607',
    active: true,
    lastLoginAt: '2018-11-20T21:28:38.412Z'
  },
  {
    id: 19,
    username: 'idir\\rawhiteh',
    clients: [],
    givenName: 'Rachel',
    familyName: 'Whitehouse',
    email: 'rachel.whitehouse@gov.bc.ca',
    phoneNumber: '250-378-8406',
    active: true,
    lastLoginAt: '2018-11-21T20:51:06.127Z'
  },
  {
    id: 51,
    username: 'idir\\cfell',
    clients: [],
    givenName: 'Cynthia',
    familyName: 'Fell',
    email: 'cynthia.fell@gov.bc.ca',
    phoneNumber: '250-398-4321',
    active: true,
    lastLoginAt: '2018-11-22T22:27:46.912Z'
  },
  {
    id: 53,
    username: 'idir\\smortens',
    clients: [],
    givenName: 'Sarah',
    familyName: 'Mortenson',
    email: 'sarah.mortenson@gov.bc.ca',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-11-21T20:53:20.750Z'
  },
  {
    id: 21,
    username: 'idir\\rgarciad',
    clients: [],
    givenName: 'Rene',
    familyName: 'Garcia-Daguer',
    email: 'rene.garciadaguer@gov.bc.ca',
    phoneNumber: '250-378-8477',
    active: true,
    lastLoginAt: '2018-11-27T21:25:03.790Z'
  },
  {
    id: 22,
    username: 'idir\\asiemen',
    clients: [],
    givenName: 'Alisa',
    familyName: 'Siemens',
    email: 'alisa.siemens@gov.bc.ca',
    phoneNumber: '250-442-5426',
    active: true,
    lastLoginAt: '2018-11-28T17:31:12.827Z'
  },
  {
    id: 41,
    username: 'idir\\zoesimon',
    clients: [],
    givenName: 'Zoe',
    familyName: 'Simon',
    email: 'zoe.simon@gov.bc.ca',
    phoneNumber: '250-371-6500',
    active: true,
    lastLoginAt: '2018-11-28T21:48:04.376Z'
  },
  {
    id: 3,
    username: 'kyubinhan',
    clients: [],
    givenName: 'Kyubin',
    familyName: 'Han',
    email: 'kyubinhan@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-11-20T00:41:20.213Z'
  },
  {
    id: 12,
    username: 'idir\\carmes',
    clients: [],
    givenName: 'Chris',
    familyName: 'Armes',
    email: 'chris.armes@gov.bc.ca',
    phoneNumber: '250-398-4362',
    active: true,
    lastLoginAt: '2018-11-28T17:12:58.723Z'
  },
  {
    id: 39,
    username: 'idir\\bwheatle',
    clients: [],
    givenName: 'Barb',
    familyName: 'Wheatley',
    email: 'barb.wheatley@gov.bc.ca',
    phoneNumber: '250-371-6500',
    active: true,
    lastLoginAt: '2018-11-28T22:13:24.387Z'
  },
  {
    id: 27,
    username: 'idir\\dilbrown',
    clients: [],
    givenName: 'Diane',
    familyName: 'Brown',
    email: 'diane.l.brown@gov.bc.ca',
    phoneNumber: '250-395-7815',
    active: true,
    lastLoginAt: '2018-11-22T19:46:50.420Z'
  },
  {
    id: 13,
    username: 'idir\\kjames',
    clients: [],
    givenName: 'Kassia',
    familyName: 'James',
    email: 'kassia.james@gov.bc.ca',
    phoneNumber: '250-398-4364',
    active: true,
    lastLoginAt: '2018-11-27T18:24:25.960Z'
  },
  {
    id: 65,
    username: 'bceid\\rangeadmin',
    clients: [],
    givenName: 'range',
    familyName: 'admin',
    email: 'rangeadmin@myrangebc.gov.ca',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-11-27T19:38:43.406Z'
  },
  {
    id: 52,
    username: 'idir\\krbarton',
    clients: [],
    givenName: 'Krista',
    familyName: 'Barton',
    email: 'krista.barton@gov.bc.ca',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-11-26T16:47:15.965Z'
  },
  {
    id: 14,
    username: 'idir\\momuelle',
    clients: [],
    givenName: 'Morgan',
    familyName: 'Mueller',
    email: 'morgan.mueller@gov.bc.ca',
    phoneNumber: '250-398-4364',
    active: true,
    lastLoginAt: '2018-11-22T18:15:13.515Z'
  },
  {
    id: 42,
    username: 'idir\\saschwar',
    clients: [],
    givenName: 'Sarah',
    familyName: 'Schwarz',
    email: 'sarah.schwarz@gov.bc.ca',
    phoneNumber: '250-442-4386',
    active: true,
    lastLoginAt: '2018-12-04T19:32:29.909Z'
  },
  {
    id: 15,
    username: 'idir\\maschuff',
    clients: [],
    givenName: 'Marc',
    familyName: 'Schuffert',
    email: 'marc.schuffert@gov.bc.ca',
    phoneNumber: '250-847-6329',
    active: true,
    lastLoginAt: '2018-12-03T21:51:24.751Z'
  },
  {
    id: 10,
    username: 'idir\\tnairn',
    clients: [],
    givenName: 'Trish',
    familyName: 'Nairn',
    email: 'trish.nairn@gov.bc.ca',
    phoneNumber: '250-398-4242',
    active: true,
    lastLoginAt: '2018-11-22T23:10:58.284Z'
  },
  {
    id: 23,
    username: 'idir\\tgrafton',
    clients: [],
    givenName: 'Taylor',
    familyName: 'Grafton',
    email: 'taylor.grafton@gov.bc.ca',
    phoneNumber: '250-614-7427',
    active: true,
    lastLoginAt: '2018-11-22T00:15:10.036Z'
  },
  {
    id: 1,
    username: 'rangestaff',
    clients: [],
    givenName: 'Range',
    familyName: 'Staff',
    email: 'amir+1@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-12-03T20:18:22.840Z'
  },
  {
    id: 47,
    username: 'idir\\willshaw',
    clients: [],
    givenName: 'William',
    familyName: 'Shaw',
    email: 'william.shaw@gov.bc.ca',
    phoneNumber: '250-784-1239',
    active: true,
    lastLoginAt: '2018-11-22T16:23:33.186Z'
  },
  {
    id: 66,
    username: 'idir\\lmoore',
    clients: [],
    givenName: 'Lisa',
    familyName: 'Moore',
    email: 'lisa.moore@gov.bc.ca',
    phoneNumber: null,
    active: false,
    lastLoginAt: '2018-11-27T17:15:27.602Z'
  },
  {
    id: 40,
    username: 'idir\\avolo',
    clients: [],
    givenName: 'Andrew',
    familyName: 'Volo',
    email: 'andrew.volo@gov.bc.ca',
    phoneNumber: '250-371-6222',
    active: true,
    lastLoginAt: '2018-11-28T17:51:15.953Z'
  },
  {
    id: 63,
    username: 'bceid\\rangestaff',
    clients: [],
    givenName: 'Range',
    familyName: 'Staff',
    email: 'rangestaff@myrange.gov.ca',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-11-27T00:47:12.364Z'
  },
  {
    id: 2,
    username: 'rangeadmin',
    clients: [],
    givenName: 'Range',
    familyName: 'Admin',
    email: 'kyubin+1@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-12-05T00:29:01.859Z'
  },
  {
    id: 4,
    username: 'bceid\\kyubinhan711',
    clients: [],
    givenName: 'Kyub',
    familyName: 'Han',
    email: 'kyubin@freshworks.io',
    phoneNumber: null,
    active: true,
    lastLoginAt: '2018-12-04T23:35:24.812Z'
  },
  {
    id: 20,
    username: 'idir\\rmctavis',
    clients: [],
    givenName: 'Ried',
    familyName: 'McTavish',
    email: 'ried.mctavish@gov.bc.ca',
    phoneNumber: '250-378-8487',
    active: true,
    lastLoginAt: '2018-12-05T00:02:13.135Z'
  },
  {
    id: 54,
    username: 'bceid\\april.ludgate',
    clients: ['09999903'],
    givenName: 'April',
    familyName: 'Ludgate',
    email: 'april.ludgate@example.com',
    phoneNumber: null,
    active: true,
    lastLoginAt: null
  }
]

export default mockUsers
