export const STORE_SSO_AUTH_DATA = 'STORE_SSO_AUTH_DATA';
export const STORE_USER = 'STORE_USER';
export const SIGN_OUT = 'SIGN_OUT';

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export const OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL';
export const CLOSE_CONFIRMATION_MODAL = 'CLOSE_CONFIRMATION_MODAL';

export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const SUCCESS_PAGINATED = 'SUCCESS_PAGINATED';

export const STORE_AGREEMENTS = 'STORE_AGREEMENTS';
export const STORE_AGREEMENT_WITH_ALL_PLANS = 'STORE_AGREEMENT_WITH_ALL_PLANS';
export const STORE_PLAN = 'STORE_PLAN';
export const PLAN_UPDATED = 'PLAN_UPDATED';
export const ADD_GRAZING_SCHEDULE = 'ADD_GRAZING_SCHEDULE';
export const UPDATE_GRAZING_SCHEDULE = 'UPDATE_GRAZING_SCHEDULE';
export const DELETE_GRAZING_SCHEDULE = 'DELETE_GRAZING_SCHEDULE';

export const STORE_REFERENCES = 'STORE_REFERENCES';
export const STORE_ZONES = 'STORE_ZONES';
export const ZONE_UPDATED = 'ZONE_UPDATED';
export const STORE_USERS = 'STORE_USERS';
export const USER_UPDATED = 'USER_UPDATED';
export const STORE_CLIENTS = 'STORE_CLIENTS';
