export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const SUCCESS_PAGINATED = 'SUCCESS_PAGINATED';
export const ERROR = 'ERROR';
export const DATA_CHANGED = 'DATA_CHANGED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USER_PROFILE_CHANGE = 'USER_PROFILE_CHANGE';

export const OPEN_TOAST_MESSAGE = 'OPEN_TOAST_MESSAGE';
export const CLOSE_TOAST_MESSAGE = 'CLOSE_TOAST_MESSAGE';
