export const AUTH = 'AUTH';
export const COMMON = 'COMMON';
export const TOAST = 'TOAST';
export const MODAL = 'MODAL';

export const AGREEMENTS = 'AGREEMENTS';
export const PLAN = 'PLAN';
export const CLIENT = 'CLIENT';
export const SEARCH_AGREEMENTS = 'SEARCH_AGREEMENTS';
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';
export const UPDATE_CLIENT_ID_OF_USER = 'UPDATE_CLIENT_ID_OF_USER';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_ZONES = 'GET_ZONES';
export const GET_USERS = 'GET_USERS';

export const GET_PLAN = 'GET_PLAN';
export const UPDATE_PLAN_STATUS = 'UPDATE_PLAN_STATUS';
export const CREATE_PASTURE = 'CREATE_PASTURE';
export const DELETE_SCHEUDLE = 'DELETE_SCHEUDLE';
export const DELETE_SCHEUDLE_ENTRY = 'DELETE_SCHEUDLE_ENTRY';
export const CREATE_MINISTER_ISSUE_AND_ACTIONS = 'CREATE_MINISTER_ISSUE_AND_ACTIONS';
export const UPDATE_MINISTER_ISSUE_AND_ACTIONS = 'UPDATE_MINISTER_ISSUE_AND_ACTIONS';
export const DELETE_MANAGEMENT_CONSIDERATION = 'DELETE_MANAGEMENT_CONSIDERATION';
export const CREATE_AMENDMENT = 'CREATE_AMENDMENT';
