export const AUTHENTICATION = "AUTHENTICATION";
export const SEARCH_AGREEMENTS = "SEARCH_AGREEMENTS";
export const AGREEMENTS = "AGREEMENTS";

// export const ALBUMS = "ALBUMS";
// export const ARTISTS = "ARTISTS";
// export const LIBRARY = "LIBRARY";

// export const SEARCH_ARTIST = "SEARCH_ARTIST";
// export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
// export const FETCH_LIBRARY = "FETCH_LIBRARY";

// export const FETCH_FAVORITE_ALBUM = "FETCH_FAVORITE_ALBUM";
// export const FETCH_UNFAVORITE_ALBUM = "FETCH_UNFAVORITE_ALBUM";
