export const AUTH = 'AUTH';
export const COMMON = 'COMMON';
export const TOAST = 'TOAST';

export const AGREEMENTS = 'AGREEMENTS';
export const PLAN = 'PLAN';
export const CLIENT = 'CLIENT';
export const SEARCH_AGREEMENTS = 'SEARCH_AGREEMENTS';
export const UPDATE_USER_ID_OF_ZONE = 'UPDATE_USER_ID_OF_ZONE';
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';
export const UPDATE_CLIENT_ID_OF_USER = 'UPDATE_CLIENT_ID_OF_USER';

export const GET_PLAN = 'GET_PLAN';
export const GET_PLAN_PDF = 'GET_PLAN_PDF';
export const UPDATE_PLAN_STATUS = 'UPDATE_PLAN_STATUS';
export const UPDATE_AGREEMENT_ZONE = 'UPDATE_AGREEMENT_ZONE';
export const CREATE_RUP_SCHEDULE = 'CREATE_RUP_SCHEDULE';
export const UPDATE_RUP_SCHEDULE = 'UPDATE_RUP_SCHEDULE';
export const DELETE_GRAZING_SCHEUDLE = 'DELETE_GRAZING_SCHEUDLE';
export const DELETE_GRAZING_SCHEUDLE_ENTRY = 'DELETE_GRAZING_SCHEUDLE_ENTRY';
