export const isBundled = process.env.NODE_ENV === 'production';

export const LOCAL_STORAGE_KEY = {
  AUTH: 'range-web-auth',
  USER: 'range-web-user',
  REFERENCE: 'range-web-reference',
};

export const TOAST_TIMEOUT = 9000;
export const NUMBER_OF_LIMIT_FOR_NOTE = 140;

export const PLAN_STATUS = {
  PENDING: 'P',
  COMPLETED: 'O',
  DRAFT: 'D',
  CREATED: 'C',
  CHANGE_REQUESTED: 'R',
  STAFF_DRAFT: 'SD',
  WRONGLY_MADE_WITHOUT_EFFECT: 'WM',
  STANDS_WRONGLY_MADE: 'SW',
  STANDS: 'S',
  NOT_APPROVED_FURTHER_WORK_REQUIRED: 'NF',
  NOT_APPROVED: 'NA',
  APPROVED: 'A',
  SUBMITTED_FOR_REVIEW: 'SR',
  SUBMITTED_FOR_FINAL_DECISION: 'SFD',
  RECOMMEND_READY: 'RR',
  RECOMMEND_NOT_READY: 'RNR',
  RECOMMEND_FOR_SUBMISSION: 'RFS',
  READY_FOR_FINAL_DECISION: 'RFD',
  AWAITING_CONFIRMATION: 'AC',
};

export const APPROVED_PLAN_STATUSES = [
  PLAN_STATUS.APPROVED, PLAN_STATUS.STANDS, PLAN_STATUS.STANDS_WRONGLY_MADE,
];

export const EDITABLE_PLAN_STATUSES = [
  PLAN_STATUS.CREATED, PLAN_STATUS.DRAFT, PLAN_STATUS.CHANGE_REQUESTED,
  PLAN_STATUS.RECOMMEND_NOT_READY, PLAN_STATUS.NOT_APPROVED_FURTHER_WORK_REQUIRED,
];

export const REQUIRE_NOTES_PLAN_STATUSES = [
  PLAN_STATUS.CHANGE_REQUESTED, PLAN_STATUS.STANDS_WRONGLY_MADE,
  PLAN_STATUS.NOT_APPROVED_FURTHER_WORK_REQUIRED, PLAN_STATUS.RECOMMEND_NOT_READY,
];

export const FEEDBACK_REQUIRED_FROM_STAFF_PLAN_STATUSES = [
  PLAN_STATUS.SUBMITTED_FOR_FINAL_DECISION, PLAN_STATUS.SUBMITTED_FOR_REVIEW,
];

export const AMENDMENT_TYPE = {
  MINOR: 'MNA',
  MANDATORY: 'MA',
  INITIAL: 'A',
};

export const CONFIRMATION_OPTION = {
  CONFIRM: 'Confirm',
  REQUEST: 'Request clarification or changes',
};

export const CONFIRMATION_MODAL_ID = {
  MANAGE_ZONE: 'MANAGE_ZONE',
  MANAGE_CLIENT: 'MANAGE_CLIENT',
  UPDATE_PLAN_STATUS: 'UPDATE_PLAN_STATUS',
  DELETE_GRAZING_SCHEDULE: 'DELETE_GRAZING_SCHEDULE',
  DELETE_GRAZING_SCHEDULE_ENTRY: 'DELETE_GRAZING_SCHEDULE_ENTRY',
  SUBMIT_PLAN: 'SUBMIT_PLAN',
};

export const REFERENCE_KEY = {
  AGREEMENT_EXEMPTION_STATUS: 'AGREEMENT_EXEMPTION_STATUS',
  AGREEMENT_TYPE: 'AGREEMENT_TYPE',
  PLAN_STATUS: 'PLAN_STATUS',
  LIVESTOCK_TYPE: 'LIVESTOCK_TYPE',
  LIVESTOCK_IDENTIFIER_TYPE: 'LIVESTOCK_IDENTIFIER_TYPE',
  MINISTER_ISSUE_TYPE: 'MINISTER_ISSUE_TYPE',
  MINISTER_ISSUE_ACTION_TYPE: 'MINISTER_ISSUE_ACTION_TYPE',
  CLIENT_TYPE: 'CLIENT_TYPE',
  AMENDMENT_TYPE: 'AMENDMENT_TYPE',
};

export const IMAGE_SRC = {
  NAV_LOGO: '/navbar_logo.png',
  COW_PIC: '/cow.jpg',
  LOGIN_LOGO: '/login_logo.png',
  SIGNIN_BACKGROUND: '/signin_background.jpg',
  LOGIN_PARAGRAPH3: '/login_paragraph3.jpg',
  LOGIN_PARAGRAPH4: '/login_paragraph4.jpg',
  LOGIN_PARAGRAPH5: '/login_paragraph5.jpg',
  BASIC_INFORMATION_ICON: '/icon_basicinformation.png',
  PASTURES_ICON: '/icon_pastures.png',
  SCHEDULES_ICON: '/icon_schedules.png',
  MINISTER_ISSUES_ICON: '/icon_ministersissues.png',
  ADDITIONAL_REQS_ICON: 'icon_additionalreqs.png',
  INVASIVE_PLANTS_ICON: 'icon_invasiveplants.png',
  MANAGEMENT_ICON: 'icon_management.png',
  MAP_ICON: 'icon_map.png',
};

export const CLIENT_TYPE = {
  PRIMARY: 'A',
  OTHER: 'B',
};

export const DATE_FORMAT = {
  SERVER_SIDE: 'YYYY-MM-DDTHH:mm:ss.SSSZ',
  CLIENT_SIDE: 'MMMM D, YYYY',
  CLIENT_SIDE_WITH_HOURS: 'MMM D, YYYY (HH:mm a)',
  CLIENT_SIDE_WITHOUT_YEAR: 'MMM D',
};

export const USER_ROLE = {
  ADMINISTRATOR: 'myra_admin',
  RANGE_OFFICER: 'myra_range_officer',
  AGREEMENT_HOLDER: 'myra_client',
};

export const ELEMENT_ID = {
  RUP_STICKY_HEADER: 'rup__sticky-header',
  BASIC_INFORMATION: 'rup__basic-information',
  PASTURES: 'rup__pastures',
  GRAZING_SCHEDULE: 'rup__grazing-schedule',
  MINISTER_ISSUES: 'rup__minister-issues',
  RUP_ZONE_DROPDOWN: 'rup__zone-dropdown',
  SIGN_OUT: 'sign-out',
  MANAGE_ZONE_ZONES_DROPDOWN: 'manage-zone__zone-dropdown',
  MANAGE_ZONE_CONTACTS_DROPDOWN: 'manage-zone__contact-dropdown',
  LOGIN_BUTTON: 'login-button',
  LOGIN_IDIR_BUTTON: 'login-idir-button',
  LOGIN_BCEID_BUTTON: 'login-bceid-button',
  SEARCH_TERM: 'searchTerm',
  MANAGE_CLIENT_USERS_DROPDOWN: 'manage-client__users-dropdown',
  MANAGE_CLIENT_CLIENTS_DROPDOWN: 'manage-client__clients-dropdown',
};
